theme: jekyll-theme-slate
  
# Site settings
title: Natalia Melnik, Dr. phil
email: natalia.melnik@ovgu.de
description: " " #"PhD in Psychology" #Shapes, objects, gestalts, perceptual organization, and peripheral appearance
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://natalia-melnik.github.io"# "http://appearancelab.org" # the base hostname & protocol for your site
#github_username: 
#linkedin_username: 
orcid_id: 0000-0002-8321-0702
# google_scholar_id: 

# Other options
#permalink: blog/:year/:month/:title/
#jobtitle: "Post doc"
#excerpt_separator: "<!--more-->"

google_analytics: G-0CQNV9DG41

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
plugins:
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
